apiVersion: v1
kind: ConfigMap
metadata:
  name: queueforge-config
  namespace: queueforge
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"
  REDIS_HOST: "queueforge-redis.queueforge.svc.cluster.local"
  REDIS_PORT: "6379"
