apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: queueforge
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'queueforge-api'
        static_configs:
          - targets: ['queueforge-service:3000']
