version: 2
updates:
  # ─── NPM Packages Updates ──────────────────────────────────────────────────
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"

  # ─── Docker Container Images Updates ────────────────────────────────────────
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  # ─── GitHub Actions Workflows Updates ──────────────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
