apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueforge-daemon
  namespace: queueforge
  labels:
    app: queueforge-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueforge-daemon
  template:
    metadata:
      labels:
        app: queueforge-daemon
    spec:
      serviceAccountName: queueforge-sa
      containers:
        - name: daemon
          image: queueforge/daemon:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: queueforge-config
            - secretRef:
                name: queueforge-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
