/**
 * Error codes representing specific application, system, and network failures in QueueForge
 */
export const enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  DELIVERY_TIMEOUT = 'DELIVERY_TIMEOUT',
  CIRCUIT_OPEN = 'CIRCUIT_OPEN',
  RATE_LIMITED = 'RATE_LIMITED',
  DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
  REDIS_CONNECTION_FAILED = 'REDIS_CONNECTION_FAILED',
  MAX_RETRIES_EXCEEDED = 'MAX_RETRIES_EXCEEDED',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RESULT_ALREADY_EXISTS = 'RESULT_ALREADY_EXISTS',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
